[build]
  command = "ng build --configuration production && ng run ngx-isr-demo:serverless:production"
  publish = "dist/ngx-isr-demo/browser"

[[plugins]]
  package = "@netlify/plugin-angular-universal"